defmodule BubbleEx.AppTree.Render.Readme do
  @moduledoc """
  Layer 2 root files: README.md (overview + honest coverage), AGENTS.md
  (how a consuming agent rebuilds the app from this tree), MANIFEST.json.
  """

  @doc """
  Renders the root files. `opts[:schema]` (default `true`) reflects whether
  `data/schema.dbml` was actually produced for this export — when `false`
  the AGENTS.md navigation omits the schema.dbml pointer and MANIFEST.json
  records `"schema_dbml" => false`.
  """
  @spec render(map(), map(), map(), keyword()) :: [
          {String.t(), {:json, term()} | {:text, iodata()}}
        ]
  def render(app, manifest, coverage, opts \\ []) do
    schema? = Keyword.get(opts, :schema, true)

    manifest_json =
      manifest
      |> Map.put("coverage", coverage_json(coverage))
      |> Map.put("schema_dbml", schema?)

    [
      {"README.md", {:text, readme(app, coverage)}},
      {"AGENTS.md", {:text, agents(schema?)}},
      {"MANIFEST.json", {:json, manifest_json}}
    ]
  end

  defp coverage_json(coverage) do
    Map.new(coverage, fn {dim, %{total: t, rendered: r}} ->
      {Atom.to_string(dim), %{"total" => t, "rendered" => r}}
    end)
  end

  defp count(app, key), do: map_size(app[key] || %{})

  defp readme(app, coverage) do
    """
    # #{app["_id"] || "app"} — AppTree export

    _Generated by BubbleEx.AppTree — do not edit. Layer-1 `.json` files are the
    lossless ground truth; every `.md` file is a regenerated view of them._

    ## Contents

    - Pages: #{count(app, "pages")}
    - Components: #{count(app, "element_definitions")}
    - Backend workflows: #{count(app, "api")}
    - Data types: #{count(app, "user_types")}
    - Option sets: #{count(app, "option_sets")}
    - Styles: #{count(app, "styles")}

    ## Rendering coverage

    - Actions rendered semantically: #{coverage.actions.rendered}/#{coverage.actions.total}
    - Expressions rendered: #{coverage.expressions.rendered}/#{coverage.expressions.total}

    Anything unrendered is explicitly marked in the `.md` views with a pointer
    to its raw `.json` file. Partial rendering is never presented as complete.

    ## Navigation

    Start with `AGENTS.md`. `MANIFEST.json` maps every Bubble id to its file.
    Each page folder holds `page.json` (raw), `OUTLINE.md` (element tree),
    `WORKFLOWS.md` (events → actions) and `workflows/` (raw, one file each).
    """
  end

  @nav_steps [
    "Read `MANIFEST.json` first: `ids` maps every Bubble id (keyed `<kind>:<bubble-id>`, e.g. `page:pgA`) to a name and file path.",
    "Per page: `OUTLINE.md` is the visual hierarchy, `WORKFLOWS.md` the behavior.",
    {:schema, "`data/schema.dbml` is the database schema; `data/types/` has the raw fields."},
    "`api/API.md` lists backend workflows (server-side endpoints/jobs).",
    "`styles/STYLES.md` is the design-token table; `settings/SETTINGS.md` the app config."
  ]

  defp agents(schema?) do
    nav =
      @nav_steps
      |> Enum.flat_map(fn
        {:schema, text} -> if schema?, do: [text], else: []
        text -> [text]
      end)
      |> Enum.with_index(1)
      |> Enum.map_join("\n", fn {text, n} -> "#{n}. #{text}" end)

    """
    # Rebuilding this app from the AppTree export

    This tree was generated from a Bubble.io `.bubble.json` export. It has two
    layers: `.json` files are the lossless ground truth; `.md` files are
    generated, readable views. When an `.md` view says something is
    unrendered, open the `.json` file it points to.

    ## How to navigate

    #{nav}

    ## Bubble → code concept map

    | Bubble concept | Code concept |
    |---|---|
    | pages | routes / views |
    | workflows | event handlers |
    | api (backend workflows) | endpoints / background jobs |
    | user_types | database schema / models |
    | option_sets | enums |
    | element_definitions | shared/reusable components |
    | styles | design tokens |

    ## Semantics worth knowing

    - Element ids (e.g. `el123`) are referenced across files; resolve them via
      `MANIFEST.json` or the name annotations in the `.md` views.
    - `[bracketed]` fragments in text are dynamic expressions evaluated at
      runtime (user data, page state).
    - Workflows are ordered action lists; `TriggerCustomEvent` calls another
      workflow like a function call.
    - Option set values and their attributes live in `data/option-sets/*.json`.
    """
  end
end
