defmodule BubbleEx.Db.Convex do
  @moduledoc """
  Encodes a parsed Bubble database map (see `BubbleEx.Db.Reader`) into a Convex
  `schema.ts`: a `defineSchema` wrapping one `defineTable` per table group, with
  each column rendered as a `v` validator from `convex/values`.

  The emit is intentionally honest about what the Bubble IR can and cannot carry:

    * `:reference` columns become `v.string()` (Bubble stores text ids, not Convex
      document ids; a migrator must re-key to `v.id("table")` after data import).
    * `:enum` columns become `v.string()` (the IR records the option-set name but
      not its member values, so `v.union(v.literal(...))` is impossible).
    * Structured Bubble `:custom` types (`bubble_geo_address`, `bubble_*_range`,
      ...) become `v.any()` (their shapes are unknown); `bubble_image`/`bubble_file`
      become `v.string()`.
    * `:utc_datetime_usec` becomes `v.float64()` (Convex stores timestamps as
      ms-since-epoch numbers).
    * `is_array: true` columns become `v.array(inner)`.
    * `:api` group tables are external placeholders with no Convex analog and are
      omitted, mirroring `BubbleEx.Db.Sql.Postgres`.

  Display names are sanitized into valid camelCase TypeScript identifiers. The
  `:naming` opt selects the source: `:proper` (default) uses Bubble display names,
  `:id` uses the raw Bubble ids.
  """

  @behaviour BubbleEx.Db.Encoder

  @type opts :: [naming: :proper | :id, external_types: :preserve | :opaque | :legacy]

  @header """
  // convex/schema.ts
  // Generated by BubbleEx.
  // NOTE: :reference columns -> v.string() (Bubble text ids, not Convex document ids; re-key after data migration).
  // NOTE: :enum columns -> v.string() (option-set member values are not in the IR).
  // NOTE: :api group tables are omitted.
  import { defineSchema, defineTable } from "convex/server";
  import { v } from "convex/values";
  """

  @impl true
  @spec encode(map(), opts()) :: {:ok, String.t()}
  def encode(parsed_map, opts \\ []) do
    plan =
      Keyword.get_lazy(opts, :_external_plan, fn ->
        BubbleEx.Db.Encoder.Plan.build(parsed_map, opts)
      end)

    opts = Keyword.put(opts, :_external_plan, plan)

    tables =
      parsed_map
      |> Map.get(:tables, [])
      |> Enum.reject(&(&1.group == :api))
      |> prepare_tables(parsed_map, opts)

    table_blocks = Enum.map_join(tables, "\n", &encode_table(&1, opts))

    external = encode_external_types(parsed_map, opts)

    schema =
      @header <>
        "\n" <>
        external <>
        if(external == "", do: "", else: "\n\n") <>
        "export default defineSchema({\n" <> table_blocks <> "});\n"

    {:ok, schema}
  end

  defp encode_table(table, opts) do
    columns = Enum.reject(table.columns, & &1.deleted)

    field_lines = Enum.map_join(columns, "\n", &encode_field(&1, opts))
    name = identifier(table_name(table, opts))

    "  #{name}: defineTable({\n#{field_lines}\n  }),\n"
  end

  defp encode_field(column, opts) do
    name = identifier(field_name(column, opts))
    base = "    #{name}: #{convex_type(column.type, opts)},"

    case field_comment(column.type, column.primary_key) do
      nil -> base
      comment -> base <> " // " <> comment
    end
  end

  # Trailing-comment policy: flag the lossy / re-key cases so a migrator knows
  # where the honest emit diverges from the ideal Convex type.
  defp field_comment(_type, true), do: "primary key (Bubble _id, text)"
  defp field_comment(%{type: :reference}, _pk), do: "reference -> re-key to v.id(...)"
  defp field_comment(%{type: :enum}, _pk), do: "enum -> option set (member values not in IR)"
  defp field_comment(_type, _pk), do: nil

  # Type mapping (IR -> Convex `v` validator) -----------------------------------

  defp convex_type(%{is_array: true} = type, opts), do: "v.array(" <> base_type(type, opts) <> ")"
  defp convex_type(type, opts), do: base_type(type, opts)

  defp base_type(%{type: :reference}, _opts), do: "v.string()"
  defp base_type(%{type: :enum}, _opts), do: "v.string()"
  defp base_type(%{type: :api}, _opts), do: "v.string()"
  defp base_type(%{type: :external, target: target}, opts), do: external_validator(target, opts)
  defp base_type(%{type: :opaque_external}, _opts), do: "v.any()"
  defp base_type(%{type: :custom, custom_type: "bubble_image"}, _opts), do: "v.string()"
  defp base_type(%{type: :custom, custom_type: "bubble_file"}, _opts), do: "v.string()"
  defp base_type(%{type: :custom}, _opts), do: "v.any()"
  defp base_type(%{type: :utc_datetime_usec}, _opts), do: "v.float64()"
  defp base_type(%{type: :boolean}, _opts), do: "v.boolean()"
  defp base_type(%{type: :float}, _opts), do: "v.float64()"
  defp base_type(%{type: :string}, _opts), do: "v.string()"
  defp base_type(_type, _opts), do: "v.string()"

  # Naming + identifier sanitization --------------------------------------------

  # :proper (default) uses display names; :id uses the Bubble ids.
  defp table_name(table, opts), do: by_naming(opts, table.name, table.id)

  # The injected primary key is surfaced under a stable, descriptive name so the
  # generated schema reads cleanly regardless of the source id ("_id"/"Display").
  defp field_name(%{primary_key: true}, _opts), do: "bubbleId"
  defp field_name(column, opts), do: by_naming(opts, column.name, column.id)

  defp by_naming(opts, proper, id) do
    case Keyword.get(opts, :naming, :proper) do
      :id -> id
      _ -> proper
    end
  end

  # Turns an arbitrary Bubble name into a valid camelCase TS identifier: split on
  # camelCase boundaries first, then on non-alphanumeric runs, lower-case the
  # first word, capitalize the rest, and prefix a `field_` guard when the result
  # would start with a digit or be empty.
  defp identifier(raw) do
    words =
      raw
      |> String.replace(~r/([a-z0-9])([A-Z])/, "\\1 \\2")
      |> String.split(~r/[^A-Za-z0-9]+/, trim: true)

    case words do
      [] ->
        "field"

      [first | rest] ->
        camel = String.downcase(first) <> Enum.map_join(rest, "", &capitalize_word/1)
        if String.match?(camel, ~r/^[0-9]/), do: "field" <> camel, else: camel
    end
  end

  defp capitalize_word(word) do
    {head, tail} = String.split_at(word, 1)
    String.upcase(head) <> tail
  end

  defp encode_external_types(_parsed_map, opts) do
    if Keyword.get(opts, :external_types, :legacy) == :preserve do
      plan = plan(opts)

      plan.order
      |> Enum.map(&Map.fetch!(plan.nodes, &1))
      |> Enum.map_join("\n", &external_definition(&1, opts))
    else
      ""
    end
  end

  defp external_definition(external, opts) do
    fields =
      Enum.map_join(external.fields, "\n", fn field ->
        name = BubbleEx.Db.Encoder.Plan.field_name(plan(opts), external.id, field)

        "  #{identifier(name)}: v.optional(v.union(#{external_expr(field, external.id, opts)}, v.null())),"
      end)

    "const #{external_validator(external.id, opts)} = v.object({\n#{fields}\n});"
  end

  defp external_expr(
         %{type: %{type: :scalar, scalar: scalar, cardinality: cardinality}},
         _parent,
         _opts
       ) do
    base =
      %{
        text: "v.string()",
        number: "v.float64()",
        boolean: "v.boolean()",
        date: "v.string()",
        date_unix: "v.float64()"
      }[scalar]

    if cardinality == :many, do: "v.array(#{base})", else: base
  end

  defp external_expr(
         %{id: field_id, type: %{type: :external, target: target, cardinality: cardinality}},
         parent,
         opts
       ) do
    fallback? =
      BubbleEx.Db.Encoder.Plan.cycle_edge?(plan(opts), parent, field_id) or
        not BubbleEx.Db.Encoder.Plan.resolved?(plan(opts), target)

    if fallback?,
      do: if(cardinality == :many, do: "v.array(v.any())", else: "v.any()"),
      else:
        if(cardinality == :many,
          do: "v.array(#{external_validator(target, opts)})",
          else: external_validator(target, opts)
        )
  end

  defp external_expr(_, _, _), do: "v.any()"

  defp external_validator(id, opts),
    do: identifier(BubbleEx.Db.Encoder.Plan.name(plan(opts), id)) <> "Validator"

  defp plan(opts), do: Keyword.fetch!(opts, :_external_plan)

  defp prepare_tables(tables, parsed_map, opts) do
    mode = Keyword.get(opts, :external_types, :legacy)

    resolved =
      parsed_map
      |> Map.get(:external_types, [])
      |> Enum.filter(&(&1.resolution == :resolved))
      |> MapSet.new(& &1.id)

    Enum.map(tables, fn table ->
      %{table | columns: Enum.map(table.columns, &prepare_column(&1, mode, resolved))}
    end)
  end

  defp prepare_column(%{type: %{type: :external, target: target}} = column, :preserve, resolved),
    do:
      if(MapSet.member?(resolved, target),
        do: column,
        else: %{column | type: %{type: :opaque_external}}
      )

  defp prepare_column(%{type: %{type: :external}} = column, :opaque, _),
    do: %{column | type: %{type: :opaque_external}}

  defp prepare_column(%{type: %{type: :external}} = column, :legacy, _),
    do: %{column | type: %{type: :api}}

  defp prepare_column(column, _, _), do: column
end
