defmodule BubbleEx.Db.Convex do
  @moduledoc """
  Encodes a parsed Bubble database map (see `BubbleEx.Db.Reader`) into a Convex
  `schema.ts`: a `defineSchema` wrapping one `defineTable` per table group, with
  each column rendered as a `v` validator from `convex/values`.

  The emit is intentionally honest about what the Bubble IR can and cannot carry:

    * `:reference` columns become `v.string()` (Bubble stores text ids, not Convex
      document ids; a migrator must re-key to `v.id("table")` after data import).
    * `:enum` columns become `v.string()` (the IR records the option-set name but
      not its member values, so `v.union(v.literal(...))` is impossible).
    * Structured Bubble `:custom` types (`bubble_geo_address`, `bubble_*_range`,
      ...) become `v.any()` (their shapes are unknown); `bubble_image`/`bubble_file`
      become `v.string()`.
    * `:utc_datetime_usec` becomes `v.float64()` (Convex stores timestamps as
      ms-since-epoch numbers).
    * `is_array: true` columns become `v.array(inner)`.
    * `:api` group tables are external placeholders with no Convex analog and are
      omitted, mirroring `BubbleEx.Db.Sql.Postgres`.

  Display names are sanitized into valid camelCase TypeScript identifiers. The
  `:naming` opt selects the source: `:proper` (default) uses Bubble display names,
  `:id` uses the raw Bubble ids.
  """

  @behaviour BubbleEx.Db.Encoder

  @type opts :: [naming: :proper | :id]

  @header """
  // convex/schema.ts
  // Generated by BubbleEx.
  // NOTE: :reference columns -> v.string() (Bubble text ids, not Convex document ids; re-key after data migration).
  // NOTE: :enum columns -> v.string() (option-set member values are not in the IR).
  // NOTE: :api group tables are omitted.
  import { defineSchema, defineTable } from "convex/server";
  import { v } from "convex/values";
  """

  @impl true
  @spec encode(map(), opts()) :: {:ok, String.t()}
  def encode(parsed_map, opts \\ []) do
    tables =
      parsed_map
      |> Map.get(:tables, [])
      |> Enum.reject(&(&1.group == :api))

    table_blocks = Enum.map_join(tables, "\n", &encode_table(&1, opts))

    schema = @header <> "\nexport default defineSchema({\n" <> table_blocks <> "});\n"

    {:ok, schema}
  end

  defp encode_table(table, opts) do
    columns = Enum.reject(table.columns, & &1.deleted)

    field_lines = Enum.map_join(columns, "\n", &encode_field(&1, opts))
    name = identifier(table_name(table, opts))

    "  #{name}: defineTable({\n#{field_lines}\n  }),\n"
  end

  defp encode_field(column, opts) do
    name = identifier(field_name(column, opts))
    base = "    #{name}: #{convex_type(column.type)},"

    case field_comment(column.type, column.primary_key) do
      nil -> base
      comment -> base <> " // " <> comment
    end
  end

  # Trailing-comment policy: flag the lossy / re-key cases so a migrator knows
  # where the honest emit diverges from the ideal Convex type.
  defp field_comment(_type, true), do: "primary key (Bubble _id, text)"
  defp field_comment(%{type: :reference}, _pk), do: "reference -> re-key to v.id(...)"
  defp field_comment(%{type: :enum}, _pk), do: "enum -> option set (member values not in IR)"
  defp field_comment(_type, _pk), do: nil

  # Type mapping (IR -> Convex `v` validator) -----------------------------------

  defp convex_type(%{is_array: true} = type), do: "v.array(" <> base_type(type) <> ")"
  defp convex_type(type), do: base_type(type)

  defp base_type(%{type: :reference}), do: "v.string()"
  defp base_type(%{type: :enum}), do: "v.string()"
  defp base_type(%{type: :api}), do: "v.string()"
  defp base_type(%{type: :custom, custom_type: "bubble_image"}), do: "v.string()"
  defp base_type(%{type: :custom, custom_type: "bubble_file"}), do: "v.string()"
  defp base_type(%{type: :custom}), do: "v.any()"
  defp base_type(%{type: :utc_datetime_usec}), do: "v.float64()"
  defp base_type(%{type: :boolean}), do: "v.boolean()"
  defp base_type(%{type: :float}), do: "v.float64()"
  defp base_type(%{type: :string}), do: "v.string()"
  defp base_type(_type), do: "v.string()"

  # Naming + identifier sanitization --------------------------------------------

  # :proper (default) uses display names; :id uses the Bubble ids.
  defp table_name(table, opts), do: by_naming(opts, table.name, table.id)

  # The injected primary key is surfaced under a stable, descriptive name so the
  # generated schema reads cleanly regardless of the source id ("_id"/"Display").
  defp field_name(%{primary_key: true}, _opts), do: "bubbleId"
  defp field_name(column, opts), do: by_naming(opts, column.name, column.id)

  defp by_naming(opts, proper, id) do
    case Keyword.get(opts, :naming, :proper) do
      :id -> id
      _ -> proper
    end
  end

  # Turns an arbitrary Bubble name into a valid camelCase TS identifier: split on
  # camelCase boundaries first, then on non-alphanumeric runs, lower-case the
  # first word, capitalize the rest, and prefix a `field_` guard when the result
  # would start with a digit or be empty.
  defp identifier(raw) do
    words =
      raw
      |> String.replace(~r/([a-z0-9])([A-Z])/, "\\1 \\2")
      |> String.split(~r/[^A-Za-z0-9]+/, trim: true)

    case words do
      [] ->
        "field"

      [first | rest] ->
        camel = String.downcase(first) <> Enum.map_join(rest, "", &capitalize_word/1)
        if String.match?(camel, ~r/^[0-9]/), do: "field" <> camel, else: camel
    end
  end

  defp capitalize_word(word) do
    {head, tail} = String.split_at(word, 1)
    String.upcase(head) <> tail
  end
end
