defmodule Mix.Tasks.Wtf.Verify do
  @shortdoc "Structural verification of a generated project (advisory)"
  @moduledoc """
  Runs the structural verification pack (WTF-386) in the owner's
  repository of a project generated by bubble_ex
  (`BubbleEx.Target.Phoenix.Structural.project/2`). A dev-only tool: it
  refuses to run with `MIX_ENV=prod`.

      mix wtf.verify structural --app APP_ID [--root DIR] [--git-sha SHA]
                                [--out DIR] [--json]

  It checks that the generated files are unchanged
  (`.wtf/generated.json`), that the project compiles without warnings,
  passes format and Credo, that its migrations are in sync with its
  resources (`mix ash.codegen --check`), and that every authorization
  bypass in owned `lib/` code is accounted for
  (`BubbleEx.Target.Phoenix.Structural.Bypasses`): a `# bubble:ignores_privacy
  <token>` comment on or above it, where the token is a workflow that
  ignores privacy rules in Bubble (inside that workflow's body), a
  `scaffold:<purpose>` the generator wrote there (`.wtf/bypasses.json`),
  or `decision:<key>` (not verifiable here: there is no decision store).
  The checks that need the Bubble model (symbol and policy coverage,
  determinism) run at generation; the summary lists what did not run
  here and why.

  **Structural, not behavioural**: a green run says the project is
  consistent with what was generated, not that it behaves like the Bubble
  app. **Advisory**: the files checked are the implementer's to edit
  (see `mix help wtf.task`; trusted verification is WTF-411).

    * `--app` - the Bubble app ID the results are for (required)
    * `--root` - the project root (default: the current directory)
    * `--git-sha` - the commit checked, recorded in each result
    * `--out` - write each `BubbleEx.Verify.Result` as `<id>.json` and
      the summary as `structural.summary.json` into this directory
      (results are CI artifacts: do not commit them)
    * `--json` - print the summary as JSON

  Exit status 1 when a check does not pass.
  """
  use Mix.Task

  alias BubbleEx.Target.Phoenix.Structural
  alias BubbleEx.Verify.Result

  @switches [root: :string, app: :string, git_sha: :string, out: :string, json: :boolean]

  @impl Mix.Task
  def run(argv) do
    if Mix.env() == :prod,
      do: Mix.raise("mix wtf.verify is a development tool; not in MIX_ENV=prod")

    case OptionParser.parse(argv, strict: @switches) do
      {opts, ["structural"], []} -> structural(opts)
      {_, _, [_ | _] = invalid} -> Mix.raise("unknown options: #{inspect(invalid)}")
      _ -> Mix.raise("usage: mix wtf.verify structural --app APP_ID (see mix help wtf.verify)")
    end
  end

  defp structural(opts) do
    app = opts[:app] || Mix.raise("--app APP_ID is required: the Bubble app ID")
    root = Keyword.get(opts, :root, ".")
    now = DateTime.utc_now() |> DateTime.truncate(:second)

    report =
      case Structural.project(root, app: app, now: now, git_sha: opts[:git_sha]) do
        {:ok, report} -> report
        {:error, e} -> Mix.raise(Exception.message(e))
      end

    if dir = opts[:out], do: write(dir, report)

    if opts[:json],
      do: Mix.shell().info(Structural.summary_json(report)),
      else: print(report)

    raise_unless_passing(report)
  end

  defp raise_unless_passing(report) do
    failing = for r <- report.results, r.status != :pass, do: r.check
    known = for k <- Map.get(report, :known, []), do: "#{k.check}: #{k.issue}"
    known_note = if known == [], do: "", else: "; known failures: #{Enum.join(known, ", ")}"

    if failing != [],
      do:
        Mix.raise(
          "structural verification did not pass: #{Enum.join(failing, ", ")}#{known_note} " <>
            "(advisory: not verified)"
        )
  end

  defp write(dir, report) do
    File.mkdir_p!(dir)

    for result <- report.results,
        do: File.write!(Path.join(dir, result.id <> ".json"), Result.to_json(result))

    File.write!(Path.join(dir, "structural.summary.json"), Structural.summary_json(report))
  end

  defp print(report) do
    shell = Mix.shell()
    shell.info(Structural.statement())
    shell.info("advisory: not verified (WTF-411)\n")

    for r <- report.results do
      shell.info("#{r.status}  #{r.id}#{if r.reason, do: " - " <> r.reason, else: ""}")

      for entry <- Enum.take(r.diff, 20),
          do: shell.info("    " <> diff_line(entry))

      if length(r.diff) > 20, do: shell.info("    … #{length(r.diff) - 20} more")

      if output = Map.get(report, :outputs, %{})[r.id],
        do: shell.info(output |> String.split("\n") |> Enum.map_join("\n", &("    | " <> &1)))
    end

    for k <- Map.get(report, :known, []),
        do: shell.info("\nknown failure: #{k.check} (#{k.issue}): #{k.reason}")

    shell.info("\nnot run here:")
    for %{check: c, reason: why} <- report.not_run, do: shell.info("  #{c}: #{why}")
  end

  defp diff_line(entry) do
    entry
    |> Map.delete(:op)
    |> Enum.sort()
    |> Enum.map_join(" ", fn {k, v} -> "#{k}=#{v}" end)
    |> then(&"#{entry.op} #{&1}")
  end
end
