# Regenerates lib/bubble_ex/model/connector_request/english.ex, the letter
# bigram model `BubbleEx.Model.ConnectorRequest.Reader.safe_name?/1` uses to
# tell names from random tokens (WTF-374), from an English word list:
#
#     mix run scripts/english_letter_pairs.exs [/usr/share/dict/american-english]
#     mix format lib/bubble_ex/model/connector_request/english.ex
#
# The committed model was generated from Debian's `wamerican` 2020.12.07-4
# (SCOWL, Kevin Atkinson; see the licence notice in the generated file).
# Words of letters only, lowercased, each framed by `^` and `$`; every pair
# of `^a-z` × `a-z$` gets ln((count + 0.5) / (row total + 0.5 × 28)), in
# thousandths of a nat, rounded.

path = List.first(System.argv()) || "/usr/share/dict/american-english"
target = "lib/bubble_ex/model/connector_request/english.ex"

words =
  path
  |> File.stream!()
  |> Stream.map(&String.trim/1)
  |> Stream.filter(&Regex.match?(~r/\A[A-Za-z]+\z/, &1))
  |> Enum.map(&String.downcase/1)

counts =
  Enum.reduce(words, %{}, fn word, acc ->
    ("^" <> word <> "$")
    |> String.graphemes()
    |> Enum.chunk_every(2, 1, :discard)
    |> Enum.reduce(acc, fn pair, acc -> Map.update(acc, Enum.join(pair), 1, &(&1 + 1)) end)
  end)

rows =
  Enum.reduce(counts, %{}, fn {pair, n}, acc ->
    Map.update(acc, String.first(pair), n, &(&1 + n))
  end)

# Integers as Elixir source, digits grouped by `_` from five digits.
number = fn n ->
  digits = n |> abs() |> Integer.to_string()

  grouped =
    if String.length(digits) < 5,
      do: digits,
      else:
        digits
        |> String.reverse()
        |> String.graphemes()
        |> Enum.chunk_every(3)
        |> Enum.map_join("_", &Enum.join/1)
        |> String.reverse()

  if n < 0, do: "-" <> grouped, else: grouped
end

firsts = String.graphemes("^abcdefghijklmnopqrstuvwxyz")
seconds = String.graphemes("abcdefghijklmnopqrstuvwxyz$")

entries =
  for a <- firsts, b <- seconds do
    value = :math.log((Map.get(counts, a <> b, 0) + 0.5) / (Map.get(rows, a, 0) + 0.5 * 28))
    ~s("#{a}#{b}" => #{number.(round(value * 1000))})
  end

File.write!(target, """
defmodule BubbleEx.Model.ConnectorRequest.English do
  @moduledoc false

  # How English-like a lowercase word is: the mean log-probability of its
  # letter pairs (with `^` and `$` for its start and end), from a letter
  # bigram model of an English word list, in thousandths of a nat. Used by
  # `BubbleEx.Model.ConnectorRequest.Reader.safe_name?/1` to tell names
  # from random tokens. Generated by scripts/english_letter_pairs.exs.
  #
  # Word list: Debian's `wamerican` 2020.12.07-4
  # (/usr/share/dict/american-english), from SCOWL (Spell Checker Oriented
  # Word Lists) by Kevin Atkinson, http://wordlist.sourceforge.net/.
  # Only letter-pair statistics are kept here, no words. Its licence:
  #
  #   Copyright 2000-2011 by Kevin Atkinson
  #
  #   Permission to use, copy, modify, distribute and sell these word
  #   lists, the associated scripts, the output created from the scripts,
  #   and its documentation for any purpose is hereby granted without fee,
  #   provided that the above copyright notice appears in all copies and
  #   that both that copyright notice and this permission notice appear in
  #   supporting documentation. Kevin Atkinson makes no representations
  #   about the suitability of this array for any purpose. It is provided
  #   "as is" without express or implied warranty.

  @log_probabilities %{
    #{Enum.join(entries, ",\n    ")}
  }

  @doc false
  @spec score(String.t()) :: float()
  def score(word) do
    pairs = ("^" <> word <> "$") |> String.graphemes() |> Enum.chunk_every(2, 1, :discard)
    total = Enum.reduce(pairs, 0, &(&2 + Map.get(@log_probabilities, Enum.join(&1), -8000)))
    total / length(pairs) / 1000
  end
end
""")

IO.puts("wrote #{target} from #{length(words)} words")
