# Generated privacy-matrix tests (BubbleEx.Target.Ash.MatrixTests, WTF-383),
# run by scripts/ash_compile_check.sh in the background while the scratch
# project compiles:
#
#     MIX_ENV=test mix run scripts/ash_compile_check/matrix_render.exs <scratch dir>
#
# For every fixture in <scratch>/matrix_plan.json (written by render.exs:
# the fixtures with privacy rules, and the private export) the matrix
# (BubbleEx.Verify.Matrix, oracle model) is written as owner-repo files to
# <scratch>/matrix/<name>/.wtf/verification/, and its ExUnit module,
# generated from those decoded files as an owner repo would, to
# <scratch>/test/matrix/<name>_privacy_matrix_test.exs. Matrices are
# synthesized concurrently. <scratch>/matrix_index.json lists the modules
# and counts for matrix_results.exs.

alias BubbleEx.Target.Ash.MatrixTests
alias BubbleEx.Verify.Matrix

[dir] = System.argv()
plan = Path.join(dir, "matrix_plan.json") |> File.read!() |> Jason.decode!()

test_dir = Path.join(dir, "test/matrix")
File.rm_rf!(test_dir)
File.rm_rf!(Path.join(dir, "matrix"))
File.rm_rf!(Path.join(dir, "matrix_index.json"))
File.mkdir_p!(test_dir)

File.write!(Path.join(dir, "test/test_helper.exs"), """
# Generated by scripts/ash_compile_check/matrix_render.exs: start the repos
# of the privacy-matrix tests (an owner app's supervision tree does this).
for repo <- Application.fetch_env!(:ash_compile_check, :ecto_repos),
    do: {:ok, _} = repo.start_link()

ExUnit.start()
""")

load = fn
  "BUBBLE_EX_PRIVATE_EXPORT" ->
    BubbleEx.Test.SplitExport.load(System.fetch_env!("BUBBLE_EX_PRIVATE_EXPORT"))

  path ->
    path |> File.read!() |> Jason.decode!()
end

render = fn %{"name" => name, "namespace" => namespace, "repo" => repo, "app" => app_id, "source" => source} ->
  {us, index} =
    :timer.tc(fn ->
      {:ok, model} = source |> load.() |> BubbleEx.Model.build()
      {:ok, synthesized} = Matrix.synthesize(model, app: app_id)
      files = Matrix.files(synthesized)
      root = Path.join([dir, "matrix", name])

      for {path, json} <- files do
        File.mkdir_p!(Path.dirname(Path.join(root, path)))
        File.write!(Path.join(root, path), json)
      end

      # What an owner repo holds: the generator reads the decoded files.
      {:ok, plan} = MatrixTests.plan(files)
      {:ok, project} = BubbleEx.Target.Ash.map(model, [], privacy: :unverified)
      {:ok, out} = MatrixTests.render(project, plan, namespace: namespace, repo: repo)
      File.write!(Path.join(test_dir, name <> "_privacy_matrix_test.exs"), out.source)

      %{
        name: name,
        app: app_id,
        repo: repo,
        module: out.module,
        counts: out.counts,
        skipped: synthesized.report.skipped
      }
    end)

  IO.puts(
    "rendered #{name}'s privacy-matrix tests in #{div(us, 1000)} ms: " <>
      "#{index.counts["scenarios"]} scenarios, #{index.counts["ops"]} ops, " <>
      "#{index.counts["observations"]} expected observations over #{index.counts["records"]} seed records"
  )

  index
end

index =
  plan
  |> Task.async_stream(render, ordered: true, timeout: :infinity, max_concurrency: max(length(plan), 1))
  |> Enum.map(fn {:ok, index} -> index end)

File.write!(Path.join(dir, "matrix_index.json"), Jason.encode!(index, pretty: true))
