# Renders every BubbleEx.Model fixture (test/support/model/*.json), every
# target fixture (test/support/target/ash/*.json) and every expression
# fixture (test/support/expression/*.json) through BubbleEx.Target.Ash and
# BubbleEx.Target.Ash.Source into a scratch Mix project: one namespace,
# domain, repo and database per fixture. The project's dependencies are
# BubbleEx.Target.Ash.versions/0. With BUBBLE_EX_PRIVATE_EXPORT set, a
# private app export is rendered too (as `Private.App`); the scratch project
# is never committed.
#
# Each fixture's compiled privacy-rule conditions
# (BubbleEx.Target.Ash.Expressions.privacy/2) are printed with
# BubbleEx.Target.Ash.Source.expr/1 into a `<namespace>.PrivacyFilters`
# module, as a policy's `authorize_if expr(...)` would hold them, so
# `mix compile` checks them too; filters.exs and runtime.exs use them.
#
#     MIX_ENV=test mix run scripts/ash_compile_check/render.exs <scratch dir>

[dir] = System.argv()

defmodule PrivacyFilters do
  # `<namespace>.PrivacyFilters.all/0`: one entry per compiled privacy-rule
  # condition, with the relationships its actor templates need loaded.
  def module(_namespace, _actor, []), do: ""

  def module(namespace, actor, filters) do
    entries =
      Enum.map_join(filters, ",\n", fn %{type: type, rule: rule, expr: expr} ->
        """
        %{
          resource: #{namespace}.#{expr.resource},
          actor: #{namespace}.#{actor},
          type: #{inspect(type)},
          rule: #{inspect(rule)},
          actor_loads: #{inspect(loads(expr.actor_loads))},
          filter: #{BubbleEx.Target.Ash.Source.expr(expr)}
        }\
        """
      end)

    """
    defmodule #{namespace}.PrivacyFilters do
      @moduledoc false
      import Ash.Expr

      def all do
        [
    #{entries}
        ]
      end
    end
    """
  end

  # [["current_role", "workspace"]] -> [current_role: [workspace: []]]
  defp loads(paths) do
    Enum.reduce(paths, [], fn path, acc -> put_path(acc, Enum.map(path, &String.to_atom/1)) end)
  end

  defp put_path(keyword, []), do: keyword

  defp put_path(keyword, [key | rest]) do
    Keyword.update(keyword, key, put_path([], rest), &put_path(&1, rest))
  end
end

fixtures =
  for {pattern, prefix} <- [
        {"test/support/model/*.json", ""},
        {"test/support/target/ash/*.json", "target_"},
        {"test/support/expression/*.json", "expr_"}
      ],
      path <- pattern |> Path.wildcard() |> Enum.sort() do
    name = prefix <> Path.basename(path, ".json")
    {"Fixtures." <> Macro.camelize(name), name, path |> File.read!() |> Jason.decode!()}
  end

private =
  case System.get_env("BUBBLE_EX_PRIVATE_EXPORT") do
    nil -> []
    "" -> []
    path -> [{"Private.App", "private_app", BubbleEx.Test.SplitExport.load(path)}]
  end

lib = Path.join(dir, "lib/generated")
File.rm_rf!(lib)
File.mkdir_p!(lib)
File.mkdir_p!(Path.join(dir, "config"))

# A distinct last module segment per repo keeps AshPostgres' default
# migration and snapshot paths (priv/<repo>) apart.
rendered =
  for {namespace, name, app} <- fixtures ++ private do
    repo = namespace <> "Repo"
    {:ok, model} = BubbleEx.Model.build(app)
    {:ok, project} = BubbleEx.Target.Ash.map(model)
    {:ok, source} = BubbleEx.Target.Ash.Source.render(project, namespace: namespace, repo: repo)

    repo_module = """
    defmodule #{repo} do
      use AshPostgres.Repo, otp_app: :ash_compile_check

      def installed_extensions, do: ["ash-functions"]
      def min_pg_version, do: %Version{major: 16, minor: 0, patch: 0}
    end
    """

    user = Enum.find(project.resources, &(&1.source.type == "user")).module

    {:ok, privacy} = BubbleEx.Target.Ash.Expressions.privacy(model, project)
    filters = Enum.filter(privacy, & &1.expr)

    File.write!(
      Path.join(lib, name <> ".ex"),
      source <> "\n" <> repo_module <> "\n" <> PrivacyFilters.module(namespace, user, filters)
    )

    IO.puts(
      "rendered #{name} as #{namespace} (#{length(project.resources)} resources, " <>
        "#{length(filters)} privacy filters)"
    )
    {namespace, repo, name}
  end

deps = Enum.map_join(BubbleEx.Target.Ash.versions(), ", ", &inspect/1)

File.write!(Path.join(dir, "mix.exs"), """
defmodule AshCompileCheck.MixProject do
  # Generated by scripts/ash_compile_check/render.exs from
  # BubbleEx.Target.Ash.versions/0.
  use Mix.Project

  def project do
    [app: :ash_compile_check, version: "0.1.0", elixir: "~> 1.17", deps: deps()]
  end

  def application, do: [extra_applications: [:logger]]

  defp deps, do: [#{deps}]
end
""")

repos = Enum.map_join(rendered, ", ", &elem(&1, 1))
domains = Enum.map_join(rendered, ", ", &elem(&1, 0))

repo_config =
  Enum.map_join(rendered, "\n", fn {_namespace, repo, name} ->
    "config :ash_compile_check, #{repo}, url: base <> \"/ash_check_#{name}\", pool_size: 2, log: false"
  end)

File.write!(Path.join(dir, "config/config.exs"), """
import Config

base = System.get_env("ASH_COMPILE_CHECK_DB", "ecto://postgres:postgres@localhost:5432")

config :ash_compile_check, ecto_repos: [#{repos}], ash_domains: [#{domains}]
config :logger, level: :warning
#{repo_config}
""")
